//autogenerated by msp430-gen.py
#ifndef _PINS_H
#define _PINS_H

#define CLOCK_PINS        (BIT2|BIT5|BIT4)
#define CLOCK_DIR         P1DIR
#define CLOCK_SEL0        P1SEL0
#define CLOCK_SEL1        P1SEL1

#define UART_TX_PIN       BIT3
#define UART_RX_PIN       BIT4
#define UART_TX_PIN_NUM   5
#define UART_RX_PIN_NUM   6
#define UART_PINS         (UART_RX_PIN|UART_TX_PIN)
#define UART_PORT         3

//define serial pins
#define BUS_PIN_SDA       BIT1
#define BUS_PIN_SCL       BIT0

#define BUS_PINS_I2C      (BUS_PIN_SDA|BUS_PIN_SCL)

#define BUS_PIN_SCK       BIT2
#define BUS_PIN_SOMI      BIT3
#define BUS_PIN_SIMO      BIT4
  
#define BUS_PINS_SPI      (BUS_PIN_SOMI|BUS_PIN_SIMO|BUS_PIN_SCK)  

#define BUS_PINS_SER      (BUS_PINS_SPI|BUS_PINS_I2C)

//sets up the pins to use with motor all on port 5
#define MOTOR_INPUT1        BIT7  // A
#define MOTOR_INPUT2        BIT5  // B 

/* old setup
#define MOTOR_INPUT1        BIT0  //NOTE  A <-- BLK for the first breakout pin1 is fried
#define MOTOR_INPUT2        BIT2  // ~A <-- GRN
#define MOTOR_INPUT3        BIT3  //  B <-- RED
#define MOTOR_INPUT4        BIT4  // ~B <-- BLU
#define MOTOR_ENABLE        BIT5  // this is for the H bridge chip ??? not on daughter board ? guessing this is just tied high on daughter board 
*/
#endif
